version: "3"
services:
  mongo-user:
    image: mongo
    restart: always
    volumes:
      - mongo-user-data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  user-service:
    build: services/user-service
    links:
      - mongo-user:mongo
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: mongo
      DB_PORT: 27017
      DB_USER: root
      DB_PASSWORD: example

volumes:
  mongo-user-data:
